name: mood_tracker
description: Daily mood tracker with calendar sync, widgets, stats, CSV export, and notifications
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  device_calendar: ^4.3.2
  table_calendar: ^3.1.2
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  home_widget: ^0.4.1
  intl: ^0.19.0
  path_provider: ^2.0.15
  csv: ^5.0.0
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
