name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3' # or your version

      - name: Install dependencies
        run: flutter pub get

      # Run analyzer but ignore warnings (only fail on errors)
      - name: Analyze (fail on errors only)
        run: |
          flutter analyze --no-fatal-warnings --no-fatal-infos

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

