name: Flutter Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up Flutter 3.13.0
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      # 3️⃣ Install dependencies
      - name: Get dependencies
        run: flutter pub get

      # 4️⃣ Analyze code (fail on errors only)
      - name: Analyze code
        run: flutter analyze --no-fatal-warnings --no-fatal-infos

      # 5️⃣ Build Android APK
      - name: Build APK
        run: flutter build apk --release

      # 6️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
