name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.36.0'  # Use a fixed version to avoid surprises

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses
          flutter doctor --android-licenses

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release