name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Show Flutter version
        run: flutter --version

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android SDK and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses || true
          flutter doctor --android-licenses --verbose

      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Clean project (force rebuild)
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Force build APK
        run: flutter build apk --release --no-build-cache --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk