name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SKIP_JDK_VERSION_CHECK: true  # Available to all jobs in this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart & Flutter
        uses: dart-lang/setup-dart@v1
        with:
          flutter: stable

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: |
          flutter doctor --android-licenses --verbose

      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Force build APK
        run: flutter build apk --release --no-build-cache --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk