name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKIP_JDK_VERSION_CHECK: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Show Flutter version
        run: flutter --version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Fix errors
        run: sudo apt-get install -y libgtk-3-dev mesa-utils

      - name: Build APK
        run: flutter build apk --debug

      - name: List APK output
        run: ls -lh build/app/outputs/flutter-apk/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
